### ISSUE TITLE
ImportError: cannot import name 'Self' from 'typing' 

### ISSUE THREAD

**Issue by hydra3333** [DeadSix27/py-cross#2]
Hello. Using Ubuntu in a VM...
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy
```
with this command
``` 
./main.py --debug --wait ffmpeg
```
this error pops up (tail of outout)
```
   Compiling cargo-c v0.9.24+cargo-0.73.0
    Finished release [optimized] target(s) in 3m 05s
  Installing /home/u/Desktop/ds27/py-cross/work/cargohome/bin/cargo-capi
  Installing /home/u/Desktop/ds27/py-cross/work/cargohome/bin/cargo-cbuild
  Installing /home/u/Desktop/ds27/py-cross/work/cargohome/bin/cargo-cinstall
  Installing /home/u/Desktop/ds27/py-cross/work/cargohome/bin/cargo-ctest
   Installed package `cargo-c v0.9.24+cargo-0.73.0` (executables `cargo-capi`, `cargo-cbuild`, `cargo-cinstall`, `cargo-ctest`)
Traceback (most recent call last):
  File "/home/u/Desktop/ds27/py-cross/./main.py", line 1638, in <module>
    compiler = CrossCompiler()
  File "/home/u/Desktop/ds27/py-cross/./main.py", line 189, in __init__
    self.buildLLVMToolchain()
  File "/home/u/Desktop/ds27/py-cross/./main.py", line 1595, in buildLLVMToolchain
    mod = importlib.import_module("mingw_toolchain_script.llvm_toolchain_script")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/u/Desktop/ds27/py-cross/mingw_toolchain_script/llvm_toolchain_script.py", line 10, in <module>
    from typing import Self
ImportError: cannot import name 'Self' from 'typing' (/usr/lib/python3.10/typing.py)

```

Suggestions would be much appreciated.

**Comment by DeadSix27** [comment]
fixed but that error is because it's made for python 3.11 and you are using outdated 3.10, ubuntu likes outdated software
